version: '2'

services:
  kafka:
    image: spotify/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
